name: Azure Pages CI
on: [push, pull_request]
jobs:

  azure_pages_job:

    runs-on: ubuntu-latest

    name: Build And Deploy

    steps:

    - uses: actions/checkout@v1
    - shell: bash
      run: |
        cd app
        npm run build
        cd ../api
        npm install
        
    - uses: miwebst/anotherdeploy@master
      with:
        azure_pages_contenthost: 'miwebstsslinux.azurewebsites.net'
        azure_pages_api_token: ${{ secrets.AZURE_PAGES_API_TOKEN }}           
        app_artifact_location: 'app/build'
        api_artifact_location: 'api'
