on: [push, pull_request]

jobs:
  azure_pages_job:
    runs-on: ubuntu-latest
    name: Azure Pages
    steps:
    - uses: actions/checkout@v1
    - name: Build And Deploy
      id: azurepagesbuilddeploy
      uses: miwebst/basic-deploy-task@master
      with:
        app_location: 'app'
